dist: trusty

addons:
  sonarcloud:
    organization: "lovata"
    token:
      secure: "tDuVhPYz5UHNYM+X6cfPlHpVRv6dCmlTsV3FCOA6ZuVJYUSaQg7gAUlqg0KyHENbAPuRc6/2iE/Y6TEIl8R6gXGf7E056e3sKvHeruz4koVCGxhFfGVQG/MS5Otc/SOyYk0cVOqQB2jl6beAXZsFWj6PWPT+tMGwhmAExgjCzHdwn4Cg8e8bpj6xtvXTSJTri0e/NwoShtl/GXdaW9KHxfm4GVhwwu4GMvcmqO9aSZqyo/u12JK12ZmSbdlug02AhHiIg2yZ1A4hPbUh+XcNm9Tv8DNM4HP6RJgwtHwVMdMPQQsYzA0lcu9TafKKAldi6KAPro0GpFISXyV6klZgHHfVUoWy8DLPvJDj+XaDgzvQAv0hRvvDWPRC2KUNhM6gQi9v7rrhOF9R5OblipT8yBDGD5jGNGA2kY5++h39V1DCzni4h5Im14fXKpWfPl6NIwXEfDqCBV+yBc/DaRun0m49KwaShk99wOjmbznOldvd06cUeUaiyQtn6QiNbCdWA9TRQveFh1f6pQDtwtymrbbzRH8gdFkOEgbOg3ue38rV161DGB/aFWgBXMzYqwWQRKYKMKFqsWnI5dAXlU+ajmo2uHPOa85GBS3CPbxr76t9qB6quy/X448dTFrJFpa65JbbMWNzGtUTldam4OMLORIlPySI0oXjXPBOEVstaeE="
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
